version: "3.7"

services:
  registry:
    image: registry:2
    container_name: my_registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml


  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: my_registry_ui
    ports:
     - "8081:80"
    environment:
     REGISTRY_URL: http://localhost:5000 
     DELETE_IMAGES: true


volumes:
  registry-data: {}

