version: '3'

services:
  frontend:
    image: localhost:5000/my-frontend-image
    container_name: my_frontend_container  # Nom personnalisé du conteneur
    ports:
      - "3000:3000"
    networks:
      - mon_reseau

  backend:
    image: localhost:5000/my-backend-image
    container_name: my_backend_container  # Nom personnalisé du conteneur
    ports:
    - "8080:8080"
    networks:
      - mon_reseau

  postgres:
    image: localhost:5000/my_postgres
    container_name: my_postgres  # Nom personnalisé du conteneur
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - mon_reseau

networks:
  mon_reseau:
    external: true
