apiVersion: v1
kind: ResourceQuota
metadata:
  name: exam-resource-quota
  namespace: exam
spec:
  hard:
    requests.cpu: "10"   
    requests.memory: "20Gi"  
    limits.cpu: "10"    
    limits.memory: "30Gi"  