apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: admin
rules:
- apiGroups: [""] 
  resources: ["pods", "services", "configmaps", "secrets", "resourcequotas"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"] 
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
