apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: exam
  name: exam-rolebinding
subjects:
- kind: User
  name: use1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
