apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: readonly-role
rules:
- apiGroups: [""]  
  resources: ["pods", "services", "configmaps", "secrets", "resourcequotas"]
  verbs: ["get", "list", "watch"]
